### ISSUE TITLE
Add optional multipleOr tests for code & vaccine-code & intent

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-core-inferno#63]
AU Core says SHOULD support multipleOr for code and vaccine-code parameters. Please add a multipleOr test to:
* 1.3.01 Server returns valid results for Observation search by patient + code (and equivalent in other Observation profiles)
* 1.3.03 Optional Server returns valid results for Observation search by code (and equivalent in other Observation profiles)
* 1.3.10 Optional Server returns valid results for Observation search by patient + code + date (and equivalent in other Observation profiles)
* 1.16.04 Optional Server returns valid results for Immunization search by vaccine-code
* 1.16.07 Optional Server returns valid results for Immunization search by patient + vaccine-code
* 1.17.06 Optional Server returns valid results for MedicationRequest search by intent
* 1.17.08 Server returns valid results for MedicationRequest search by patient + intent
* 1.17.09 Server returns valid results for MedicationRequest search by patient + intent + status
* 1.17.10 Server returns valid results for MedicationRequest search by patient + intent + authoredon
* 1.19.02 Optional Server returns valid results for Procedure search by code
* 1.19.06 Optional Server returns valid results for Procedure search by patient + code + date

**Comment by projkov** [comment]
[ ] 1.3.01 Server returns valid results for Observation search by patient + code (and equivalent in other Observation profiles)
[ ] 1.3.03 Optional Server returns valid results for Observation search by code (and equivalent in other Observation profiles)
[ ] 1.3.10 Optional Server returns valid results for Observation search by patient + code + date (and equivalent in other Observation profiles)
[ ] 1.16.04 Optional Server returns valid results for Immunization search by vaccine-code
[ ] 1.16.07 Optional Server returns valid results for Immunization search by patient + vaccine-code
[ ] 1.17.06 Optional Server returns valid results for MedicationRequest search by intent
[ ] 1.17.08 Server returns valid results for MedicationRequest search by patient + intent
[ ] 1.17.09 Server returns valid results for MedicationRequest search by patient + intent + status
[ ] 1.17.10 Server returns valid results for MedicationRequest search by patient + intent + authoredon
[ ] 1.19.02 Optional Server returns valid results for Procedure search by code
[ ] 1.19.06 Optional Server returns valid results for Procedure search by patient + code + date

**Comment by projkov** [comment]
The fix for this issue will be merged. 
Now, multipleOr and multipleAnd requests are independent tests. It's simpler to read and understand.

https://github.com/hl7au/au-fhir-core-inferno/pull/75

**Comment by projkov** [comment]
@StephThaoOng Hello

This was fixed. Could you review it? If all good, please close the ticket

**Comment by StephThaoOng** [comment]
Server returns valid results for Observation search by patient + code and equivalent in other Observation profiles)
- Still missing multipleOR tests on **code** for this combined search

Server returns valid results for Observation search by patient + code + date (and equivalent in other Observation profiles)
- Still missing multipleOR tests on **code** for this combined search
- Still missing multipleAND tests on **date** for this combined search

Server returns valid results for Immunization search by patient + vaccine-code
- Still missing multipleOR tests on **vaccine-code** for this combined search

Server returns valid results for MedicationRequest search by patient + intent
- Still missing multipleOR tests on **intent** for this combined search

Server returns valid results for MedicationRequest search by patient + intent + status
- Still missing multipleOR tests on **intent** and **status** for this combined search

Server returns valid results for MedicationRequest search by patient + intent + authoredon
- Still missing multipleAND tests on **authoredon** (with date comparators) for this combined search

Server returns valid results for Procedure search by patient + code + date
- Still missing multipleOR tests on **code** for this combined search

**Comment by projkov** [comment]
@StephThaoOng Steph,

All tests for "multipleOr" and "multipleAnd" were implemented **separately from the combined search.**

**Comment by StephThaoOng** [comment]
> [@StephThaoOng](https://github.com/StephThaoOng) Steph,
> 
> All tests for "multipleOr" and "multipleAnd" were implemented **separately from the combined search.**
> 
> Initially, the ticket was created asking to add multiple "Or" tests to existing tests. However, when we started development, we decided not to change the working logic of the combined search parameters and made it separately with new tests.

Thanks @projkov - ack that tests for "multipleOr" and "multipleAnd" are implemented separately from the combined search for now. We'll discuss with the team (next Sprint meeting) whether this is acceptable in the longer term.

**Comment by StephThaoOng** [comment]
> > [@StephThaoOng](https://github.com/StephThaoOng) Steph,
> > All tests for "multipleOr" and "multipleAnd" were implemented **separately from the combined search.**
> > Initially, the ticket was created asking to add multiple "Or" tests to existing tests. However, when we started development, we decided not to change the working logic of the combined search parameters and made it separately with new tests.
> 
> Thanks [@projkov](https://github.com/projkov) - ack that tests for "multipleOr" and "multipleAnd" are implemented separately from the combined search for now. We'll discuss with the team (next Sprint meeting) whether this is acceptable in the longer term.

24/6 Infra&Tooling meeting - agreed that for AU Core capability testing, it is reasonable to implement tests for "multipleOr" search and "multipleAnd" search separately.
